apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "audit-log-exporter.fullname" . }}
  labels:
    {{- include "audit-log-exporter.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    resourceNames:
    - audit-log-exporter-storage-tracking
    verbs:
    - get
    - update
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - create
